### PR TITLE
Restored a testcase that was deleted by accident

### PR DESCRIPTION
**Pull request by mattijsf**
Restored a testcase that was deleted by accident in compare-duration branch

### CODE REVIEW

**Comment by mattijsf** [comment]
Interesting `    ✗ testAgo, XCTAssertEqualWithAccuracy failed: ("1431707535.45406") is not equal to ("1431707534.88636") +/- ("0.01") -`

It runs fine repeatedly on my system. Maybe due to the somewhat slow performance of travis it takes a while between loading the `DurationTestCase` class and executing the `testAgo()` `testLater()`. And the above case it even ~500ms. 

I suggest to inline the `let duration = Duration(value: 1, unit: .CalendarUnitDay)` statement in each test case.

**Comment by naoty** [comment]
Circle CI can be ignored. I forgot to disable it. But, the build error of travis cannot be ignored. It seems that a test with `XCTAssertEqualWithAccuracy` is failed. As you said, the result of this assertion depends on the system. So, this should not be used as possible. But, if you have no way other than this, `now` property should be defined and used for all date calculations.

**Comment by mattijsf** [comment]
I updated `Duration` to allow both `duration.later` and also `duration.later(someDate)` 

Basically the property `duration.later` is the same is calling the function `duration.later(NSDate())`. This addition makes the `later` and the `ago` feature even more useful in my opinion. And it should fix the test case :)

**Comment by naoty** [comment]
The addition is useful! But, `duration.later(from: date)` is more intuitive and Swift-like.

**Comment by mattijsf** [comment]
Agree, new commit incoming :)

**Comment by mattijsf** [comment]
I agree. I've included the proposed parameter.

**Comment by naoty** [comment]
@mattijsf  Thank you for the good work!

**Comment by naoty** [comment]
Released your works at `0.3.2`.

**Pull request merged**
