### PR TITLE
Fix for Swift 2.0 Beta 3

### PR DESCRIPTION
**Pull request by strawberrycode**
Fix for Swift 2.0, using migration tool + manual fix in
NSDate+Timepiece.swift

### CODE REVIEW

**Comment by naoty** [comment]
@strawberrycode Thank you for PR! Have you seen `swift-2.0` branch? I have should write about the branch at README. Sorry.

**Comment by strawberrycode** [comment]
Hi @naoty, I saw your `swift-2.0` branch, but it was not working for me with Xcode 7 Beta 3. That's why I created the `swift-2.0-fix` fork. I tried to make `swift-2.0` work, but I finally forked if from `master` because it was easier to migrate and fix (and to merge afterwards).

**Comment by naoty** [comment]
@strawberrycode I see. Would you change the target branch into `swift-2.0` branch? I want to keep `master` separated from `swift-2.0` until the stable version of Swift 2.0 is released.

**Comment by Jamonek** [comment]
Hi, stable version of Swift is released.

**Comment by naoty** [comment]
Now, v0.4.1 supports Swift 2.

**Pull request closed without merging**
