### PR TITLE
Added functions for beginning of Week and end of Week

### PR DESCRIPTION
**Pull request by irlabs**
I further extended the `beginningOfMonth` / `beginningOfDay` / `endOfMonth` / `endOfDay` functions in `NSDate+Timepiece.swift` to quickly get the first and last days of the current week.

### CODE REVIEW

**Comment by naoty** [comment]
@irlabs Thank you for a pull request. I won't implement the beginning and end of a week because the meaning of the beginning and end is arbitrary. Instead, I implemented `change(weekday:)`.

**Comment by irlabs** [comment]
Ah, thanks. I didn't notice that.  
I don't think the beginning and end is arbitrary though. Isn't NSCalendar's `firstWeekday` method there to take care of solving that?

**Comment by naoty** [comment]
I didn't the method. It will solve this problem! BTW, why did you close this PR?

**Comment by irlabs** [comment]
I closed the PR, because I optimized it using a `modulo` instead of an `if`. And I wanted to create a new pull request, when I saw your comment, so I left it closed.  I'll reopen it.

**Comment by naoty** [comment]
@irlabs Your implementations looks great! But, I would you to add some tests for it. If tests are added, I will merge this PR.

**Comment by irlabs** [comment]
I added tests for it.
I couldn't test different localizations in the same test method, though. (If you want to test with a calendar whose weeks start on a monday, you'll have to run the test with a different locale as launch argument)

**Comment by naoty** [comment]
Looks good :+1:

**Comment by irlabs** [comment]
Thanks!

**Pull request merged**
