### PR TITLE
Feature/compare duration

### PR DESCRIPTION
**Pull request by mattijsf**
- Added support to subtract two dates from each other and obtain the difference as NSTimeInterval.
- Added ability to compare Duration against NSTimeInterval

These two additations combined allows the following:
```swift
if date2 - date1 > 5.seconds { ... }
etc.
```

### CODE REVIEW

**Comment by mattijsf** [comment]
Not that I didn't allow the comparison of `NSTimeInterval` against .month / .year type of `Duration` since these can vary (e.g. leap years and such). In those cases an error is thrown that comparing agaist the those units isn't supported.

**Comment by naoty** [comment]
As you mentioned, it is very difficult to determine How long seconds `1.duration` or `1.year` duration has. I think the conversion of `Duration` into `NSTimeInterval` is essentially impossible without any context, even if the duration is `1.second`, `1.minute` or `1.hour`.

**Comment by naoty** [comment]
I checked the implementation of `1.momth` at ActiveSupport and Moment.js. At ActiveSupport, `1.month` always means 30 days and `1.year` always means 365.25 days. Moment.js is the almost same as ActiveSupport. So, I think it is better to follow these implementations.

**Comment by mattijsf** [comment]
I fully agree there! I was also in doubt wether or not to go for such an approach. I did in the end chose for the most theoratically "correct" approach. But it does make sense to go for 30 days / 365.25 days if you indeed follow the principle of least astonishment. In reality I expect the usage of month / year will be limited anyhow. It makes pratically more sense to compare against x.day or x.seconds.

I'll change that then!

**Comment by mattijsf** [comment]
> If NSTimeInterval conforms to Equatable, you don't need to implement this, only ==.
> If NSTimeInterval conforms to Comparable, you don't need to implement this, only <.

Yes, but that only works if the left hand side / right hand side are both `NSTimeInterval` In my commit I was comparing `NSTimeInterval` against `Duration`. One way to work around that is to say `5.minutes.interval` and then write the comparison as 
```swift
if date2 - date1 < 5.minutes.interval { .. }
```
As a side note, since `NSTimeInterval` is a typedef'd `Double` it is already `Equatable` & `Comparable` by nature.

Maybe I'm getting it wrong, let me know if I do :) 

What do you prefer?

**Comment by naoty** [comment]
@mattijsf Sorry for the delay. Oh, I see. Then, your implementation of the operators looks good! I feel `date2 - date1 < 5.minutes` is more intuitive than `5.minutes.interval`. But, this operation should internally convert `5.minutes` into `NSTimeInterval` to compare between `NSTimeInterval`.

**Comment by mattijsf** [comment]
I just updated https://github.com/mattijsf/Timepiece/commit/649811a8522425274f4278b3b5ea27b799bc3666 what do you think? 

I did do something different for the interval for year / quarter. I'm still not sure what's best there. Might still change it back to 365.25 

Any preference?

**Comment by mattijsf** [comment]
Whoops I just noticed I removed one of your test classes by mistake in that commit, will restore that later on :)

**Comment by naoty** [comment]
It looks great! Especially, the each definition of interval for units at `NSCalendarUnit+TImepiece` is a nice idea!

**Comment by mattijsf** [comment]
Ah! I see you merged it already :) Did you notice my comment about the TestCase I deleted by accident?

**Comment by naoty** [comment]
Oh, I missed it... :bow: Would you send a new PR to add deleted test cases?

**Comment by mattijsf** [comment]
I will! But I don't have a laptop available the coming 2 days. I will do it
Saturday / Sunday for sure!

**Comment by maelp** [comment]
I'd say even comparison with `date2 - date1 > 1.day` can be wrong since daylight saving time might add or remove an hour.

I guess there are only two correct ways to do this:
 - either replace "1.day" with eg "1.defaultDayDuration" suggesting we really compare with 24 hours, not 1 day
 - or do computations by adding the increment to one date, rather than computing the time differences between dates, eg

```
(date2 - date1) > 1.day == date2 > date1 + 1.day == date2 > NSCalendar.add(date, day: 1)
```

**Pull request merged**
